### ISSUE TITLE
Popup After reboot

### ISSUE THREAD

**Issue by schroot72** [nicoduj/homebridge-gogogate2#24]
The plugin works great for my gogogate2 ! just a feature request. After I reboot the home bridge, I always get a pop up from HomeKit the door is closed. Since I reboot periodically because of another plugin, I get this pop up frequently. Is there a way to make this optional after reboot ?

**Comment by nicoduj** [comment]
Hi, thanks for feedback. I also saw this, and I think it is because I set the door as open by default before updating its status. I could try to set it closed by default, which might be better. Will try in next  release ! Just a question : are you on master branch or 1.0.0beta ?

**Comment by schroot72** [comment]
I'm currently on the master branch

**Comment by nicoduj** [comment]
Hi, didn't find a way for the moment, but I will keep this open :) If anyone has any clue, he is welcome :)

**Comment by nicoduj** [comment]
I thnik this one is fixed, let me know if it is not the case

**Comment by schroot72** [comment]
I did an npm update homebridge-gogogate2 and a reboot, it is not solved.

**Comment by nicoduj** [comment]
Can I ask how you are rebooting homebridge ? I am interested into your logs in debug mode if possible, just in case. I don't notice this alert anymore by my side on reboot.

**Comment by schroot72** [comment]
I think the update is wrong. I use Homebridge on a Docker container on my Syno. I stop/start the container. It states the version of homnebridge-gogogate2 as 0.1.3

**Comment by nicoduj** [comment]
yeah, the plugin is not on the master branch. you have to use npm latest.

do you use config-uix and oznu docker image : it makes everything easier in my opinion

**Comment by schroot72** [comment]
i use oznu docker image, but not config-uix. I wil look into that, updating from shell is not working.

**Comment by schroot72** [comment]
oke, updated with config-uix, problem solved. thx !
